modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
[[mods]] #mandatory
# The modid of the mod
modId="hiddenthingsmod" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="0.1.1" #mandatory
# A display name for the mod
displayName="Hidden Things Mod" #mandatory
# displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Thanks for this mod goes to Java" #optional
# A text field displayed in the mod UI
authors="Love, Cheese and small house plants" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This is my mod so shut up!

No just kidding pls give feedback. :)
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.hiddenthingsmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.hiddenthingsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
